name: Terraform CI
on:
  pull_request:
    paths:
      - '**.tf'
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.0'
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan
        if: github.event_name == 'push'
        run: terraform plan -out=tfplan
      - name: Terraform Apply
        if: github.event_name == 'push'
        env:
          TF_APPLY_APPROVAL: ${{ github.event.inputs.apply_approval || 'false' }}
        run: |
          if [ "$TF_APPLY_APPROVAL" == "true" ]; then
            terraform apply -auto-approve tfplan
          else
            echo "Apply skipped (manual approval not provided)"
          fi
